{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  database.yml.erb: |
    production:
      adapter: postgresql
      encoding: unicode
      database: {{ template "unicorn.psql.database" . }}
      pool: 10
      username: {{ template "unicorn.psql.username" . }}
      password: <%= File.read("/etc/gitlab/postgres/psql-password") %>
      host: {{ template "unicorn.psql.host" . }}
      port: {{ template "unicorn.psql.port" . }}
      # load_balancing:
      #   hosts:
      #     - host1.example.com
      #     - host2.example.com
  smtp_settings.rb: |
{{ include "gitlab.smtp_settings" . | indent 4 }}
  resque.yml.erb: |
    production:
      # Redis (single instance)
      url: redis://:<%= File.read("/etc/gitlab/redis/password") %>@{{ template "unicorn.redis.host" . }}:{{ default 6379 .Values.redis.port }}
  workhorse-config.toml.erb: |
    [redis]
    URL = "tcp://{{ template "unicorn.redis.host" . }}:{{ default 6379 .Values.redis.port }}"
    Password = "<%= File.read("/etc/gitlab/redis/password") %>"
  unicorn.rb: |
    worker_processes {{ .Values.workerProcesses }}
    working_directory "/home/git/gitlab"
    listen "0.0.0.0:{{ .Values.service.internalPort }}", :tcp_nopush => true
    timeout {{ .Values.workerTimeout }}
    pid "/home/git/unicorn.pid"
    preload_app true

    before_fork do |server, worker|
      old_pid = "#{server.config[:pid]}.oldbin"
      if old_pid != server.pid
        begin
          sig = (worker.nr + 1) >= server.worker_processes ? :QUIT : :TTOU
          Process.kill(sig, File.read(old_pid).to_i)
        rescue Errno::ENOENT, Errno::ESRCH
        end
      end

      ActiveRecord::Base.connection.disconnect! if defined?(ActiveRecord::Base)
    end

    after_fork do |server, worker|
      ActiveRecord::Base.establish_connection if defined?(ActiveRecord::Base)
      defined?(::Prometheus::Client.reinitialize_on_pid_change) && Prometheus::Client.reinitialize_on_pid_change
    end

    ENV['GITLAB_UNICORN_MEMORY_MIN'] = (400 * 1 << 20).to_s
    ENV['GITLAB_UNICORN_MEMORY_MAX'] = (650 * 1 << 20).to_s
  gitlab.yml.erb: |
    production: &base
      gitlab:
        host: {{ template "gitlabHost" . }}
        https: {{ hasPrefix "https://" (include "gitlabUrl" .) }}
        trusted_proxies:
        {{- if .Values.trusted_proxies }}
{{ toYaml .Values.trusted_proxies | indent 10 }}
        {{- end }}
        time_zone: {{ .Values.global.time_zone | quote }}
        email_from: {{ template "gitlab.email.from" . }}
        email_display_name: {{ .Values.global.email.display_name | quote }}
        email_reply_to: {{ template "gitlab.email.reply_to" . }}
        email_subject_suffix: {{ .Values.global.email.subject_suffix | quote }}
        default_projects_features:
          issues: true
          merge_requests: true
          wiki: true
          snippets: true
          builds: true
          container_registry: true
      incoming_email:
        enabled: false
      artifacts:
        enabled: true
      lfs:
        enabled: {{ eq .Values.lfs.enabled true }}
        object_store:
          enabled: true
          remote_directory: {{ .Values.lfs.bucket }}
          direct_upload: true
          background_upload: false
          proxy_download: {{ eq .Values.lfs.proxy_download true }}
          {{- if .Values.minio.enabled }}
          connection:
            provider: AWS
            region: us-east-1
            aws_access_key_id: "<%= File.read('/etc/gitlab/minio/accesskey') %>"
            aws_secret_access_key: "<%= File.read('/etc/gitlab/minio/secretkey') %>"
            host: {{ template "minioHost" . }}
            endpoint: {{ template "unicorn.minio.endpoint" . }}
            path_style: true
          {{- else if .Values.lfs.connection}}
          connection:
{{ toYaml .Values.lfs.connection | indent 12}}
          {{- end }}
      uploads:
        enabled: {{ eq .Values.uploads.enabled true }}
        object_store:
          enabled: true
          remote_directory: {{ .Values.uploads.bucket }}
          direct_upload: true
          background_upload: false
          proxy_download: {{ eq .Values.uploads.proxy_download true }}
          {{- if .Values.minio.enabled }}
          connection:
            provider: AWS
            region: us-east-1
            aws_access_key_id: "<%= File.read('/etc/gitlab/minio/accesskey') %>"
            aws_secret_access_key: "<%= File.read('/etc/gitlab/minio/secretkey') %>"
            host: {{ template "minioHost" . }}
            endpoint: {{ template "unicorn.minio.endpoint" . }}
            path_style: true
          {{- else if .Values.uploads.connection}}
          connection:
{{ toYaml .Values.uploads.connection | indent 12}}
          {{- end }}
      pages:
        enabled: false
      mattermost:
        enabled: false
      gravatar:
      gitlab_ci:
      ldap:
        enabled: false
      kerberos:
        enabled: false
      omniauth:
      {{- if not .Values.omniauth.providers }}
        enabled: false
      {{- else }}
        enabled: true
        providers:
        {{- range $index, $entry := .Values.omniauth.providers }}
          - name: '{{ $entry.name }}'
            app_id: '<%= File.read('/etc/gitlab/omniauth/{{ $entry.name }}/app_id') %>'
            app_secret: '<%= File.read('/etc/gitlab/omniauth/{{ $entry.name}}/app_secret') %>'
        {{-  if $entry.args }}
            args:
{{ toYaml $entry.args | indent 14 }}
        {{-  end }}
        {{- end }}
      {{- end }}
      shared:
      gitaly:
        client_path: /home/git/gitaly/bin
        token: "<%= File.read('/etc/gitlab/gitaly/gitaly_token') %>"
      repositories:
        storages: # You must have at least a `default` storage path.
          default:
            path: /var/opt/gitlab/repo
            gitaly_address: tcp://{{ template "unicorn.gitaly.host" . }}:{{ default 8075 .Values.gitaly.port }}
      backup:
        path: "tmp/backups"   # Relative paths are relative to Rails.root (default: tmp/backups/)
      gitlab_shell:
        path: /home/git/gitlab-shell/
        hooks_path: /home/git/gitlab-shell/hooks/
        secret_file: /etc/gitlab/shell/.gitlab_shell_secret
        upload_pack: true
        receive_pack: true
      workhorse:
      git:
        bin_path: /usr/bin/git
      webpack:
      monitoring:
        ip_whitelist:
          - 0.0.0.0/0
        sidekiq_exporter:
      extra:
        {{- if .Values.extra }}
{{ toYaml .Values.extra | indent 8 }}
        {{- end }}
      rack_attack:
        git_basic_auth:
          {{- if .Values.rack_attack.git_basic_auth.enabled }}
{{ toYaml .Values.rack_attack.git_basic_auth | indent 10 }}
          {{- end }}
      ## Registry Integration
      registry:
        enabled: true
        host: {{ template "unicorn.registry.host" . }}
        {{- if .Values.registry.port }}
        port: {{ .Values.registry.port }}
        {{- end }}
        api_url: {{ default "http" .Values.registry.api.protocol }}://{{ template "unicorn.registry.api.host" . }}:{{ default 5000 .Values.registry.api.port }}
        key: /etc/gitlab/registry/gitlab-registry.key
        issuer: {{ .Values.registry.tokenIssuer }}
  configure: |
    set -e
    mkdir -p /init-secrets/redis /init-secrets/shell /init-secrets/gitaly \
      /init-secrets/registry /init-secrets/postgres /init-secrets/rails-secrets
    cp /init-config/redis/password /init-secrets/redis/password
    cp /init-config/shell/.gitlab_shell_secret /init-secrets/shell/.gitlab_shell_secret
    cp /init-config/gitaly/gitaly_token /init-secrets/gitaly/gitaly_token
    cp /init-config/registry/gitlab-registry.key /init-secrets/registry/gitlab-registry.key
    cp /init-config/postgres/psql-password /init-secrets/postgres/psql-password
    cp /init-config/rails-secrets/secrets.yml /init-secrets/rails-secrets/secrets.yml
    if [ -e /init-config/minio ]; then
      mkdir -p /init-secrets/minio
      cp /init-config/minio/* /init-secrets/minio/
    fi
    if [ -e /init-config/omniauth ]; then
      mkdir -p /init-secrets/omniauth
      cp -r /init-config/omniauth/* /init-secrets/omniauth/
    fi
    if [ -e /init-config/smtp/smtp-password ]; then
      mkdir -p /init-secrets/smtp
      cp /init-config/smtp/smtp-password /init-secrets/smtp/
    fi
# Leave this here - This line denotes end of block to the parser.
{{- end }}
