---
apiVersion: v1
name: operator
version: 1.8.2
appVersion: 11.10.2
description: Gitlab operator for managing upgrades
keywords:
- gitlab
- operator
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/gitlab/charts/operator
- https://gitlab.com/charts/components/gitlab-operator
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
