# Default values for sidekiq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.com/charts/components/gitlab-operator@sha256
  tag: 30d875871102cc6257489feba11d5b115e81d66f1d4b832aa888bb35bd44c83b
  pullSecrets: []
  # pullPolicy: IfNotPresent

# Which version of the operator to deploy
version: 0.1

init:
  resources:
    requests:
      cpu: 50m

install:
  # Install the operator as well
  enabled: true
  image:
    repository: gcr.io/google_containers/hyperkube
    tag: v1.9.0
    pullSecrets: []
    #pullPolicy: IfNotPresent

resources:
  # limits:
  #  cpu: 1
  #  memory: 2G
  requests:
    cpu: 100m
    memory: 64M
