{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  database.yml.erb: |
    production:
      adapter: postgresql
      encoding: unicode
      database: {{ template "gitlab.psql.database" . }}
      pool: 10
      username: {{ template "gitlab.psql.username" . }}
      password: <%= File.read("/etc/gitlab/postgres/psql-password") %>
      host: {{ template "gitlab.psql.host" . }}
      port: {{ template "gitlab.psql.port" . }}
      # load_balancing:
      #   hosts:
      #     - host1.example.com
      #     - host2.example.com
  resque.yml.erb: |
    production:
      # Redis (single instance)
      url: redis://:<%= File.read("/etc/gitlab/redis/password") %>@{{ template "gitlab.redis.host" . }}:{{ template "gitlab.redis.port" }}
  gitlab.yml: |
    production: &base
      gitlab:
      repositories:
        storages:
          default:
            path: /var/opt/gitlab/repo
            gitaly_address: tcp://localhost:8075
  configure: |
    set -e
    mkdir -p /init-secrets/redis /init-secrets/postgres /init-secrets/rails-secrets
    cp /init-config/redis/password  /init-secrets/redis/password
    cp /init-config/postgres/psql-password  /init-secrets/postgres/psql-password
    cp /init-config/rails-secrets/secrets.yml /init-secrets/rails-secrets/secrets.yml
# Leave this here - This line denotes end of block to the parser.
{{- end }}
