{{- if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "migrations.jobname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: configure
          command: ['sh', '/config/configure']
          image: busybox
          volumeMounts:
          - name: migrations-config
            mountPath: /config
            readOnly: true
          - name: init-migrations-secrets
            mountPath: /init-config
            readOnly: true
          - name: migrations-secrets
            mountPath: /init-secrets
            readOnly: false
      restartPolicy: OnFailure
{{- include "pullsecrets" .Values.image | indent 6}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - /scripts/wait-for-deps
            - /scripts/db-migrate
          {{ template "gitlab.imagePullPolicy" . }}
          env:
            - name: GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-runner
                  key: runner-registration-token
            - name: CONFIG_TEMPLATE_DIRECTORY
              value: '/var/opt/gitlab/templates'
            - name: CONFIG_DIRECTORY
              value: '/var/opt/gitlab/config/gitlab/'
            {{- if .Values.initialRootPassword}}
            - name: GITLAB_ROOT_PASSWORD
              value: {{ include "migrations.validate_root_password" . | required "migrations.initialRootPassword needs to be more than 6 characters" | quote }}
            {{- end }}
          volumeMounts:
            - name: migrations-config
              mountPath: '/var/opt/gitlab/templates'
            - name: migrations-secrets
              mountPath: '/etc/gitlab'
              readOnly: true
            - name: migrations-secrets
              mountPath: /home/git/gitlab/config/secrets.yml
              subPath: rails-secrets/secrets.yml
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: migrations-config
        configMap:
          name: {{ template "fullname" . }}
      - name: init-migrations-secrets
        projected:
          defaultMode: 0400
          sources:
          - secret:
              name: {{ .Values.railsSecrets.secret }}
              items:
                - key: {{ .Values.railsSecrets.key | quote }}
                  path: rails-secrets/secrets.yml
          - secret:
              name: {{ coalesce .Values.redis.password.secret .Values.global.redis.password.secret }}
              items:
                - key: {{ coalesce .Values.redis.password.key .Values.global.redis.password.key }}
                  path: redis/password
          - secret:
              name: {{ template "gitlab.psql.password.secret" . }}
              items:
                - key: {{ template "gitlab.psql.password.key" . }}
                  path: postgres/psql-password
      - name: migrations-secrets
        emptyDir:
          medium: "Memory"
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
