# Default values for gitlab-chart.
# This is a YAML-formatted file.

global:
  hosts:
    domain: example.local
    https: true
  ingress:
    configureCertmanager: false
    annotations: {}
    enabled: true
  psql:
    password: {}

certmanager:
  # Install cert-manager chart. Set to false if you already have cert-manager
  # installed or if you are not using cert-manager.
  install: true
  # Configure an ACME Issuer in cert-manager. Only used if configure==true
  issuer:
    server: https://acme-v01.api.letsencrypt.org/directory
  # Other cert-manager configurations from upstream
  # See https://github.com/kubernetes/charts/tree/master/stable/cert-manager#configuration
  rbac:
    create: true

redis-ha:
  nameOverride: redis
  enabled: false

# nginx:
#   ingress:
#     enabled: true
#     acme: true
#
# kube-lego:
#   enabled: true
#   config:
#     LEGO_EMAIL: email@domain.tld
#     # LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
#   rbac:
#     create: true
#
# registry:
#   enabled: false
#
# minio:
#   enabled: false
#
# redis:
#   enabled: false
#
# gitlab:
#   omnibus:
#     enabled: false
#   migrations:
#     enabled: false
#   unicorn:
#     enabled: false
#   sidekiq:
#     enabled: false
#   gitaly:
#     enabled: false
#   gitlab-shell:
#     enabled: false
