# Default values for gitlab-chart.
# This is a YAML-formatted file.

global:
  hosts:
    domain: example.local
    https: true
  ingress:
    configureCertmanager: true
    annotations: {}
    enabled: true
  psql:
    password: {}

certmanager:
  # Install cert-manager chart. Set to false if you already have cert-manager
  # installed or if you are not using cert-manager.
  install: true
  # Other cert-manager configurations from upstream
  # See https://github.com/kubernetes/charts/tree/master/stable/cert-manager#configuration
  rbac:
    create: true

prometheus:
  install: true
  rbac:
    create: true
  alertmanager:
    enabled: false
  alertmanagerFiles:
    alertmanager.yml: {}
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false

redis-ha:
  nameOverride: redis
  enabled: false

# registry:
#   enabled: false
#
# minio:
#   enabled: false
#
# redis:
#   enabled: false
#
# gitlab:
#   omnibus:
#     enabled: false
#   migrations:
#     enabled: false
#   unicorn:
#     enabled: false
#   sidekiq:
#     enabled: false
#   gitaly:
#     enabled: false
#   gitlab-shell:
#     enabled: false
