# Default values for gitlab-chart.
# This is a YAML-formatted file.

global:
  hosts:
    domain: example.local
    https: true

# nginx:
#   ingress:
#     enabled: true
#     acme: true
#
# kube-lego:
#   enabled: true
#   config:
#     LEGO_EMAIL: email@domain.tld
#     # LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
#   rbac:
#     create: true
#
# registry:
#   enabled: false
#
# minio:
#   enabled: false
#
# redis:
#   enabled: false
#
# gitlab:
#   omnibus:
#     enabled: false
#   migrations:
#     enabled: false
#   unicorn:
#     enabled: false
#   sidekiq:
#     enabled: false
#   gitaly:
#     enabled: false
#   gitlab-shell:
#     enabled: false
