# Default values for gitlab-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nginx:
  ingress:
    enabled: true

registry:
  enabled: false

redis:
  enabled: false

gitlab:
  omnibus:
    enabled: false
  unicorn:
    enabled: false
  gitlab-shell:
    enabled: false

global:
  hosts:
    domain: example.local
    https: false
