# Default values for omnibus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab/gitlab-ee
  tag: nightly
  pullPolicy: Always
service:
  name: omnibus
  type: ClusterIP
  clusterIP: '0.0.0.0'
  ports:
    psql: 5432

enabled: true
# config items
external_url: http://gitlab.example.local
trusted_proxies:
- "127.0.0.1/24"
- "10.0.0.0/8"
- "172.16.0.0/12"
- "192.168.0.0/16"
# redis
redis:
  # port: 6397
  # database: 0
  # password provided as file, via Secret
  serviceName: redis
  password:
    secret: gitlab-redis
    key: redis-password
# enabled components
psql:
  shared_buffers: "1MB"
  # port: '5432'
  # database: 'gitlabhq_production'
  # username: 'gitlab'
  password:
    secret: gitlab-postgres
    key: psql-password

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: true

    ## postgres data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 10Gi

    ## If subPath is set mount a sub folder of a volume instead of the root of the volume.
    ## This is especially handy for volume plugins that don't natively support sub mounting (like glusterfs).
    ##
    subPath: ""

    ## if volumeName is set, use this existing PersistentVolume
    # volumeName:

    ## Only bind to a volume with the following exactly matched labels with values.
    ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
    matchLabels: {}

    ## Only bind to a volume with the following exppression matched labels.
    ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
    matchExpressions: []

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 200m
    memory: 512Mi
