---
apiVersion: v1
name: unicorn
version: 0.2.0
appVersion: 11.0.0-rc13
description: HTTP server for Gitlab
keywords:
- gitlab
- unicorn
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/gitlab/charts/unicorn
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-unicorn
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
