# Default values for unicorn-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-unicorn
  tag: latest
  pullPolicy: Always
metrics:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/-/metrics"
service:
  name: unicorn
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  workhorseExternalPort: 8181
  workhorseInternalPort: 8181
enabled: true
ingress:
  enabled: true
  proxyConnectTimeout: 15
  proxyReadTimeout: 600
  proxyBodySize: "512m"
  tls: {}
    # secretName:
  annotations: {}
workerProcesses: 2
workerTimeout: 60
omniauth:
  providers: []
  # - name: google_oauth2
  #   secretName: gitlab-google-oauth2
  #   args: { access_type: 'offline', approval_prompt: '' }
railsSecrets:
  secret: rails-secrets
  key: secrets.yml
global:
  ingress:
    enabled: true
    annotations: {}
    tls: {}
      # secretName:
  hosts:
    domain: example.local
    hostSuffix:
    https: true
    gitlab: {}
      #name: gitlab.example.local
      #https: false
    registry: {}
      #name: registry.example.local
      #https: false
    minio: {}
      #name: minio.example.local
      #https: false
  psql:
    # host: '0.0.0.0'
    # port: '5432'
    # database: 'gitlabhq_production'
    # username: 'gitlab'
    serviceName: 'omnibus'
    password:
      secret: gitlab-postgres
      key: psql-password
redis:
  # host: '0.0.0.0'
  serviceName: 'redis'
  password:
    secret: gitlab-redis
    key: redis-password
psql:
  password: {}
shell:
  authToken:
    secret: gitlab-shell-secret
    key: secret
gitaly:
  # host: '0.0.0.0'
  # port: 8075
  serviceName: 'gitaly'
  authToken:
    secret: gitaly-secret
    key: token
lfs:
  enabled: true
  proxy_download: true
  # bucket:
  # connection: {}
minio:
  enabled: true
  bucket: git-lfs
  credentials:
    secret: gitlab-minio
  serviceName: 'minio-svc'
  port: 9000
registry:
  host:
  # port: 443
  api:
    protocol: http
    serviceName: registry
    port: 5000
  tokenIssuer: gitlab-issuer
  certificate:
    secret: gitlab-registry
    key: registry-auth.key
resources:
  # limits:
  #  cpu: 1
  #  memory: 2G
  requests:
    cpu: 200m
    memory: 2G
