image:
  repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-task-runner-ee
  tag: latest
  pullPolicy: Always
  pullSecrets: []
enabled: false
railsSecrets:
  secret: rails-secrets
  key: secrets.yml
global:
  hosts:
    domain: example.local
    hostSuffix:
    https: true
    gitlab: {}
    registry: {}
    minio: {}
  psql:
    # host: '0.0.0.0'
    # port: '5432'
    # database: 'gitlabhq_production'
    # username: 'gitlab'
    password: {}
  redis:
    password:
      secret: gitlab-redis
      key: redis-password
backups:
  bucketName: gitlab-backups

extra: {}

rack_attack:
  git_basic_auth:
    enabled: false
    # enabled: true
    # ip_whitelist: ["127.0.0.1"]
    # maxretry: 10
    # findtime: 60
    # bantime: 3600

trusted_proxies: []

redis:
  password: {}
psql:
  password: {}
shell:
  authToken:
    secret: gitlab-shell-secret
    key: secret
gitaly:
  # host: '0.0.0.0'
  # port: 8075
  serviceName: 'gitaly'
  authToken:
    secret: gitaly-secret
    key: token
lfs:
  enabled: true
  proxy_download: true
  # bucket:
  # connection: {}
minio:
  enabled: true
  bucket: git-lfs
  credentials:
    secret: gitlab-minio
  serviceName: 'minio-svc'
  port: 9000
registry:
  host:
  # port: 443
  api:
    protocol: http
    serviceName: registry
    port: 5000
  tokenIssuer: gitlab-issuer
  certificate:
    secret: gitlab-registry
    key: registry-auth.key
resources:
  # limits:
  #  cpu: 1
  #  memory: 2G
  requests:
    cpu: 200m
    memory: 500M
