image:
  repository: registry
  tag: '2.6'
  pullPolicy: 'IfNotPresent'
service:
  name: registry
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
  clusterIP: '0.0.0.0'

# define some sane resource requests and limitations
resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 1024Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Chart operation controls
enabled: true
registry:
  # Will be auto-populated if not present (`{{ randAlphaNum 128 | b64enc | quote }}`)
  httpSecret: ''
  storage: {}
  # Protocol/Host only. '/jwt/auth' will be appended.
  authEndpoint: 'https://gitlab.example.local'
  # Do not change this
  tokenService: 'container_registry'
  # This must match your GitLab Rails configuration
  tokenIssuer: 'gitlab-registry-issuer'
  # Public side of the certificate bundle used to sign JWT auth requests
  certBundle:
    secretName: 'gitlab-registry-certbundle'
    bundleName: 'gitlab-registry.crt'
  # if replicas is >1, shared storage MUST be used.
  replicas: 1
