{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  database.yml.erb: |
    production:
      adapter: postgresql
      encoding: unicode
      database: {{ template "sidekiq.psql.database"  . }}
      pool: 10
      username: {{ template "sidekiq.psql.username" . }}
      password: <%= File.read("/etc/gitlab/postgres/psql-password") %>
      host: {{ template "sidekiq.psql.host" . }}
      port: {{ template "sidekiq.psql.port" . }}
      # load_balancing:
      #   hosts:
      #     - host1.example.com
      #     - host2.example.com
  resque.yml.erb: |
    production:
      # Redis (single instance)
      url: redis://:<%= File.read("/etc/gitlab/redis/password") %>@{{ template "sidekiq.redis.host" . }}:{{ default 6379 .Values.redis.port }}
  gitlab.yml.erb: |
    production: &base
      gitlab:
        https: false # Set to true if using HTTPS, see installation.md#using-https for additional HTTPS configuration details
        trusted_proxies:
        email_from: example@example.com
        email_display_name: GitLab
        email_reply_to: noreply@example.com
        email_subject_suffix: ''
        default_projects_features:
          issues: true
          merge_requests: true
          wiki: true
          snippets: true
          builds: true
          container_registry: true
      incoming_email:
        enabled: false
      artifacts:
        enabled: true
      lfs:
        enabled: false
        object_store:
          enabled: false
      pages:
        enabled: false
      mattermost:
        enabled: false
      gravatar:
      registry:
      gitlab_ci:
      ldap:
        enabled: false
      kerberos:
        enabled: false
      omniauth:
        enabled: false
      shared:
      gitaly:
        client_path: /home/git/gitaly/bin
        token: "<%= File.read('/etc/gitlab/gitaly/gitaly_token') %>"
      repositories:
        storages: # You must have at least a `default` storage path.
          default:
            path: /var/opt/gitlab/repo
            gitaly_address: tcp://{{ template "sidekiq.gitaly.host" . }}:{{ default 8075 .Values.gitaly.port }}
      backup:
        path: "tmp/backups"   # Relative paths are relative to Rails.root (default: tmp/backups/)
      gitlab_shell:
        path: /home/git/gitlab-shell/
        hooks_path: /home/git/gitlab-shell/hooks/
        upload_pack: true
        receive_pack: true
      workhorse:
      git:
        bin_path: /usr/bin/git
      webpack:
      monitoring:
        ip_whitelist:
          - 127.0.0.0/8
        sidekiq_exporter:
{{- if .Values.metrics.enabled }}
          enabled: true
          address: 0.0.0.0
          port: {{ .Values.metrics.port }}
{{- end }}
      extra:
      rack_attack:
        git_basic_auth:
  configure: |
    set -e
    mkdir -p /sidekiq-secrets/redis /sidekiq-secrets/postgres \
    /sidekiq-secrets/gitaly /sidekiq-secrets/rails-secrets
    cp /init-secrets/redis/password /sidekiq-secrets/redis/password
    cp /init-secrets/gitaly/gitaly_token /sidekiq-secrets/gitaly/gitaly_token
    cp /init-secrets/postgres/psql-password /sidekiq-secrets/postgres/psql-password
    cp /init-secrets/rails-secrets/secrets.yml /sidekiq-secrets/rails-secrets/secrets.yml
# Leave this here - This line denotes end of block to the parser.
{{- end }}
