{{- if .Values.enabled -}}
{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- $releaseName := .Release.Name -}}
{{- $fullname := printf "%s-%s" $releaseName $name | trunc 63 | trimSuffix "-" -}}
{{- range .Values.pods -}}
{{- $queueName := printf "%s-%s" $fullname .name | trunc 63}}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-v1" ($queueName | trunc 60) }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-v1" ($queueName | trunc 60) }}
  minReplicas: {{ default $.Values.minReplicas .minReplicas }}
  maxReplicas: {{ default $.Values.maxReplicas .maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: {{ $.Values.hpa.targetAverageValue }}
{{- end -}}
{{- end -}}
