apiVersion: v1
name: certmanager-issuer
version: 0.1.0
appVersion: 0.2.2
description: Configuration Job to add LetsEncrypt Issuer to cert-manager
keywords:
- gitlab
- cert-manager
- tls
- letsencrypt
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/certmanager-issuer
- https://gitlab.com/gitlab-org/build/CNG/tree/master/kubectl
- https://github.com/jetstack/cert-manager
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
