{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $releaseName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: {{ eq .Values.ingress.acme true | quote }}
    ingress.kubernetes.io/proxy-body-size: {{ .Values.proxyBodySize | quote }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.name }}
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ $releaseName }}-{{ $host.serviceName }}"
              servicePort: {{ $host.servicePort }}
    {{- end -}}

  {{- if or .Values.ingress.acme .Values.ingress.tls }}
  tls:
  {{- end }}
  {{- if .Values.ingress.acme }}
    - hosts:
      {{- range $host := .Values.ingress.hosts }}
      - {{ $host.name }}
      {{- end }}
      secretName: {{ .Release.Name }}-acme-tls
  {{- end }}
  {{- if .Values.ingress.tls }}
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
