# NGINX chart provides
# - HTTP(S) Ingress services with SSL termination to all external facing services
# - TCP Ingress for gitlab-shell's SSH services
nginx:
  service:
    # loadBalancerIP: <GKE static IP address>
  serviceAccount:
    # Auto Generate the service accounts for RBAC support (requires tiller to be installed with sufficient privileges)
    autoGenerate: false
  ingress:
    enabled: true
    hosts:
      - name: registry.example.local
        serviceName: registry
        servicePort: registry
      - name: gitlab.example.local
        serviceName: unicorn
        servicePort: workhorse
  shell:
    name: gitlab-shell
    port: ssh

# Registry chart Provides services to Unicorn/Omnibus chart(s) and external clients
registry:
  enabled: true
  registry:
    replicas: 1
    # https://docs.docker.com/registry/deploying/#storage-customization
    storage:
      filesystem:
        rootdirectory: '/var/lib/registry'
      cache:
        blobdescriptor: 'inmemory'
      delete:
        enabled: true
    authEndpoint: 'http://gitlab.example.local'
    tokenIssuer: gitlab-issuer
    certBundle:
      secretName: gitlab-registry
      bundleName: registry-auth.crt

# Redis chart provides Redis services to multiple charts
redis:
  enabled: true
  password:
    secret: gitlab-redis
    key: redis-password

# GitLab sub-chart
gitlab:
    # Unicorn (and workhorse) chart
    unicorn:
      enabled: true
      gitlab_host: gitlab.example.local
      registry:
        host: registry.example.local
        port: 80
        api:
          serviceName: registry
        tokenIssuer: gitlab-issuer
        certificate:
          secret: gitlab-registry
          key: registry-auth.key
      shell:
        secret: gitlab-shell-secret
      gitaly:
        serviceName: gitaly
        auth_token:
          secret: gitaly-secret
          key: token
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    # Sidekiq chart, with split queues (see charts/gitlab/charts/sidekiq/values.yaml)
    sidekiq:
      enabled: true
      concurrency: 10
      timeout: 5
      gitaly:
        serviceName: gitaly
        auth_token:
          secret: gitaly-secret
          key: token
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    # Shell provides SSH access
    gitlab-shell:
      enabled: true
      unicorn:
        serviceName: unicorn
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
    # Gitaly provides storage & API access to Git repository data
    gitaly:
      enabled: true
      secret:
        name: gitaly-secret
        key: token
    # Handle database init and upgrade migrations, via gitlab-rails codebase
    migrations:
      enabled: true
      initial_root_password: "minikube"
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    # omnibus sub-chart (development only)
    omnibus:
      enabled: true
      # the `migrations` chart handles this.
      auto_migrate: false
      # use Redis chart
      redis:
        enabled: false
        password:
          secret: gitlab-redis
          key: redis-password
      # provide PostgreSQL services
      psql:
        enabled: true
        sql_user_password: ${echo -n '${secure-pgsql-password}gitlab' | md5sum - | cut -d ' ' -f1}
