# Global chart properties
global:
  hosts:
    domain: example.local
    https: false
    # tls:
    #   secretName:  example-local-tls

# NGINX chart provides
# - HTTP(S) Ingress services with SSL termination to all external facing services
# - TCP Ingress for gitlab-shell's SSH services
nginx:
  service:
    # loadBalancerIP: <GKE static IP address>
  serviceAccount:
    autoGenerate: true
  ingress:
    acme: true
    enabled: true

## Kube lego
kube-lego:
  enabled: true
  LEGO_EMAIL: email@domain.tld
  # LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
  rbac:
    create: true

# Registry chart Provides services to Unicorn/Omnibus chart(s) and external clients
registry:
  minio:
    enabled: true
# Redis chart provides Redis services to multiple charts
redis:
  enabled: true

# Minio chart provides Minio servics for Object Storage
minio:
  enabled: true
  defaultBuckets:
    - name: registry

# GitLab sub-chart
gitlab:
    # Unicorn (and workhorse) chart
    unicorn:
      enabled: true
      registry:
        tokenIssuer: gitlab-issuer
        certificate:
          secret: gitlab-registry
          key: registry-auth.key
      shell:
        authToken:
          secret: gitlab-shell-secret
      gitaly:
        serviceName: gitaly
        authToken:
          secret: gitaly-secret
          key: token
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password:
          secret: gitlab-postgres
    # Sidekiq chart, with split queues (see charts/gitlab/charts/sidekiq/values.yaml)
    sidekiq:
      enabled: true
      concurrency: 10
      timeout: 5
      gitaly:
        serviceName: gitaly
        authToken:
          secret: gitaly-secret
          key: token
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password:
          secret: gitlab-postgres
    # Shell provides SSH access
    gitlab-shell:
      enabled: true
      unicorn:
        serviceName: unicorn
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
    # Gitaly provides storage & API access to Git repository data
    gitaly:
      enabled: true
      authToken:
        name: gitaly-secret
        key: token
    # Handle database init and upgrade migrations, via gitlab-rails codebase
    migrations:
      enabled: true
      initialRootPassword: "minikube"
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password:
          secret: gitlab-postgres
    # omnibus sub-chart (development only)
    omnibus:
      enabled: true
      # use Redis chart
      redis:
        password:
          secret: gitlab-redis
          key: redis-password
      # provide PostgreSQL services
      psql:
        password:
          secret: gitlab-postgres
