# Global chart properties
global:
  hosts:
    domain: example.local
    https: false
    # tls:
    #   secretName:  example-local-tls

# NGINX chart provides
# - HTTP(S) Ingress services with SSL termination to all external facing services
# - TCP Ingress for gitlab-shell's SSH services
nginx:
  service:
    # loadBalancerIP: <GKE static IP address>
  acme: false
  serviceAccount:
    # Auto Generate the service accounts for RBAC support (requires tiller to be installed with sufficient privileges)
    autoGenerate: false
  ingress:
    enabled: true
  shell:
    name: gitlab-shell
    port: ssh

# Registry chart Provides services to Unicorn/Omnibus chart(s) and external clients
registry:
  enabled: true
  tokenIssuer: gitlab-issuer
  certificate:
    secret: gitlab-registry
    key: registry-auth.crt
  # See doc/charts/registry/README.md#replicas
  replicas: 1
  # https://docs.docker.com/registry/deploying/#storage-customization
  storage:
    filesystem:
      rootdirectory: '/var/lib/registry'
    cache:
      blobdescriptor: 'inmemory'
    delete:
      enabled: true

# Redis chart provides Redis services to multiple charts
redis:
  enabled: true
  password:
    secret: gitlab-redis
    key: redis-password

# GitLab sub-chart
gitlab:
    # Unicorn (and workhorse) chart
    unicorn:
      enabled: true
      registry:
        port: 80
        tokenIssuer: gitlab-issuer
        certificate:
          secret: gitlab-registry
          key: registry-auth.key
      shell:
        authToken:
          secret: gitlab-shell-secret
      gitaly:
        serviceName: gitaly
        authToken:
          secret: gitaly-secret
          key: token
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    # Sidekiq chart, with split queues (see charts/gitlab/charts/sidekiq/values.yaml)
    sidekiq:
      enabled: true
      concurrency: 10
      timeout: 5
      gitaly:
        serviceName: gitaly
        authToken:
          secret: gitaly-secret
          key: token
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    # Shell provides SSH access
    gitlab-shell:
      enabled: true
      unicorn:
        serviceName: unicorn
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
    # Gitaly provides storage & API access to Git repository data
    gitaly:
      enabled: true
      authToken:
        name: gitaly-secret
        key: token
    # Handle database init and upgrade migrations, via gitlab-rails codebase
    migrations:
      enabled: true
      initialRootPassword: "minikube"
      redis:
        serviceName: redis
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    # omnibus sub-chart (development only)
    omnibus:
      enabled: true
      # use Redis chart
      redis:
        password:
          secret: gitlab-redis
          key: redis-password
      # provide PostgreSQL services
      psql:
        sql_user_password: ${echo -n '${secure-pgsql-password}gitlab' | md5sum - | cut -d ' ' -f1}
