---
apiVersion: v1
name: gitlab-monitor
version: 2.0.5
appVersion: 4.0.0
description: Exporter for GitLab Prometheus metrics (e.g. CI, pull mirrors)
keywords:
- gitlab
- gitlab-monitor
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/gitlab/charts/gitlab-monitor
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-monitor
- https://gitlab.com/gitlab-org/gitlab-monitor
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
