apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shared-secrets.fullname" . }}
  labels:
    app: {{ template "shared-secrets.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  generate-secrets: |
{{ include (print $.Template.BasePath "/_generate_secrets.sh") . | indent 4 }}
