apiVersion: v1
name: minio
version: 0.4.3
appVersion: RELEASE.2017-12-28T01-21-00Z
description: Object storage server built for cloud applications and devops.
details: Minio used as part of GitLab deployment.
keywords:
- S3
- gitlab
home: https://minio.io
icon: https://www.minio.io/img/logo_160x160.png
sources:
- https://gitlab.com/charts/gitlab/charts/minio
- https://github.com/minio/minio
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
