# Default values for gitlab-shell.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-shell
  tag: latest
  pullSecrets: []
  pullPolicy: Always
service:
  name: gitlab-shell
  type: ClusterIP
  externalPort: 22
  internalPort: 2222

global:
  redis:
    password:
      secret: gitlab-redis
      key: redis-password

enabled: true
authToken:
   secret: gitlab-shell-secret
   key: secret
hostKeys:
  secret: gitlab-shell-host-keys
unicorn:
  serviceName: unicorn
  # host: '0.0.0.0'
  # serviceName: 'unicorn'
  # port: 8080
redis:
  password: {}
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 200m
    memory: 64Mi
maxUnavailable: 1
minReplicas: 2
maxReplicas: 10
