# Default values for gitaly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.gitlab.com/gitlab-org/build/cng/gitaly
  tag: latest
  pullPolicy: Always
service:
  name: gitaly
  type: ClusterIP
  externalPort: 8075
  internalPort: 8075
enabled: false
authToken:
  secret: gitaly-secret
  key: token
unicorn: {}
  # host: '0.0.0.0'
  # serviceName: 'unicorn'
  # port: 8080
redis:
  # host: '0.0.0.0'
  # serviceName: 'omnibus'
  password:
    secret: gitlab-redis
    key: redis-password
shell:
  authToken:
   secret: gitlab-shell-secret
   key: secret
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
