apiVersion: v1
name: shared-secrets
version: 0.1.0
description: Populates secrets needed by CNG charts
keywords:
- gitlab
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/gitlab/charts/migrations
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-rails
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
