apiVersion: v1
name: redis
version: 0.1.0
appVersion: 3.2.6
description: An advanced key-value cache and store.
details: Redis used as part of GitLab deployment.
keywords:
- redis
- gitlab
home: https://redis.io
icon: https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Redis_Logo.svg/1200px-Redis_Logo.svg.png
sources:
- https://hub.docker.com/_/redis/
- https://gitlab.com/charts/gitlab/charts/redis
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
