name: github pages

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        run: |
          value=false
          for value in $(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/users/${{ github.event.pull_request.user.login }}/orgs | jq '.[] | contains({"login":"mattermost"})')
          do
            if [[ $value ]]; then
              break
            fi
          done
          echo "IS_MEMBER=$value" >> $GITHUB_ENV
          if [[ $value ]]; then
            echo "Is a member of the Mattermost Organization"
          else
            echo "Is not a member of the Mattermost Organization"
          fi
          
      - uses: actions/checkout@v2
        if: env.IS_MEMBER == 'true'
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        if: env.IS_MEMBER == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pipenv
        if: env.IS_MEMBER == 'true'
        run: pip install pipenv

      - name: Install dependencies
        if: env.IS_MEMBER == 'true'
        run: pipenv install --dev

      - name: Build
        if: env.IS_MEMBER == 'true'
        run: make html

      - name: Deploy
        if: env.IS_MEMBER == 'true'
        uses: peaceiris/actions-gh-pages@v3.7.0-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./${{ github.event.number }}
          publish_dir: ./dist/html
          publish_branch: gh-pages
          keep_files: true
          
      - name: Add comment to PR
        if: env.IS_MEMBER == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            Newest code from ${{ github.actor}} has been published to [preview environment](https://mattermost.github.io/docs/${{ github.event.number }})
